/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachingsRouteImport } from './routes/teachings'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'

const TeachingsRoute = TeachingsRouteImport.update({
  id: '/teachings',
  path: '/teachings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/programs': typeof ProgramsRoute
  '/teachings': typeof TeachingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/programs': typeof ProgramsRoute
  '/teachings': typeof TeachingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/programs': typeof ProgramsRoute
  '/teachings': typeof TeachingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/about'
    | '/apply'
    | '/contact'
    | '/faculty'
    | '/programs'
    | '/teachings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/about'
    | '/apply'
    | '/contact'
    | '/faculty'
    | '/programs'
    | '/teachings'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/about'
    | '/apply'
    | '/contact'
    | '/faculty'
    | '/programs'
    | '/teachings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  FacultyRoute: typeof FacultyRoute
  ProgramsRoute: typeof ProgramsRoute
  TeachingsRoute: typeof TeachingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachings': {
      id: '/teachings'
      path: '/teachings'
      fullPath: '/teachings'
      preLoaderRoute: typeof TeachingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  FacultyRoute: FacultyRoute,
  ProgramsRoute: ProgramsRoute,
  TeachingsRoute: TeachingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
